### ISSUE TITLE
Linux version of the application

### ISSUE THREAD

**Issue by Brensom** [Astrarium/Astrarium#109]
Why doesn't a program written in C# have a Linux version?
If the program is written in C#, then it should be possible to run it under Mono, but I can't. Why is that?

**Comment by AlexanderKrutov** [comment]
Hi @Brensom!
That's because Astrarium has GUI written with WPF, and there are no support of WPF on Linux at the moment. There are some alternatives though (like [Avalonia](https://github.com/AvaloniaUI/Avalonia), for example), but they are not fully-compartible with WPF markup used in Astrarium and it will take a lot of time to make it cross-platform.
